### PR TITLE
No More Warnings Again

### PR DESCRIPTION
**Pull request by nigels-com**
As in https://github.com/libglui/glui/pull/57 but with less creativity.

### CODE REVIEW

**Comment by josch** [comment]
What happened with using `%z` for `size_t`?

**Comment by nigels-com** [comment]
I'm not sure that `%z` is supported on some of the older MS toolchains.  They declined to be C99 compliant, as I recall.

**Comment by josch** [comment]
@nigels-com then I guess you have no objections to me just clicking the merge button now?

**Comment by nigels-com** [comment]
Go for it if you're entirely happy with it.

**Pull request merged**
