### PR TITLE
Move GLUT header dependency from glui.h to internals

### PR DESCRIPTION
**Pull request by nigels-com**
Some recent discussion and proposals to abstract from GLUT.

This PR moves the compile-time dependency to the internals of GLUI, and out of `glui.h`

### CODE REVIEW

**Comment by mick-p1982** [comment]
I take it you realize this will break any client code that depends on glui.h to include GLUT.

I proposed this, but only to avoid conflicts, and via a test to see if GLUT is already included.

Please also add pass-through/pick-up callbacks for the missing GLUT "Func" APIs. I guess you want to do that in a piecemeal commit if so going by your M.O. But it would fit neatly into this since you're moving them already. Motion and PassiveMotion are missing (and the GLUT headers should be checked for any others.)

**Comment by mick-p1982** [comment]
BTW: I generally avoid GLU. I realize GLUT pulls it in. But if truly abstracting from GLUT hitting the user with GLU seems a little forward.

Does GLUI use the Quadric for the Rotate control? I think that control (which I kind think looks cool) could be implemented with a texture matrix if it isn't. Or a shader if not. (Maybe a shader would not go over so well with indirect rendering; but it's hard to advocate for applications hanging out in OpenGL 1.4 world.)

**Comment by nigels-com** [comment]
There was already a consolidation of the GLUT callbacks https://github.com/libglui/glui/pull/68

But if there is anything further we can deal with that in a seperate PR, if you'd like to propose one.

Yes, this is a breaking change and will require applications to include the GLUT header if they need it.  That's intended.

**Comment by nigels-com** [comment]
I agree that GLUI might not want to depend on GLU for interface or implementation, but that's a task/job for another day.  I don't see why that would be necessary to try an alternative back-end to GLUT.

**Comment by mick-p1982** [comment]
GLU is just generally deprecated. It's old and avoided by applications today. It's just a matter of professionalism. In truth there's no reason to include the OpenGL headers either. Clients might use wrappers and not want the namespace pollution.

**Comment by nigels-com** [comment]
Sure.  So we'll remove GLU when GLUI stops depending on it.

**Pull request merged**
