### PR TITLE
Tidy-up: GLUT bitmap string utility functions internal only

### PR DESCRIPTION
**Pull request by nigels-com**

### CODE REVIEW

**Comment by mick-p1982** [comment]
If FREEGLUT is used it's glutBitmapString API should be preferred. Also every god blessed GLUI_Control has a kilobyte "hash table" in its body that just holds the widths of the letters in its font (which might change.)

If you really want to help get rid of that, and if it's caching is desired popular a table for the printable (isprint) range of ASCII letters when the font is first used, housed in the font, and not in the controls. (This is sub amateur code that needs attention.)

Don't look at me to unilaterally correct these things as long as I can't get shit past Shinola.

**Comment by nigels-com** [comment]
I started experimenting with [libdrawtext](http://nuclear.mutantstargoat.com/sw/libdrawtext/) as a replacement text rendering scheme for GLUI.  For one thing modern displays are much higher resolution than provided by GLUT fonts.  But as a stop-gap I agree that making the table a singleton would be an improvement.

**Comment by mick-p1982** [comment]
This is getting complicated if libdrawtext was to be used.

I think that a GLUI should not be used in concert with a GLUT. I think GLUI should be a complete wrapper around a GLUT that is entirely opaque.

That would mean that GLUI would need to be able to represent the main window. Currently it doesn't really know about the main window (that is a window with no GLUI-fications applied.)

It would need to in a sense incorporate what Win32 to calls the non-client area. That is the title bar and so on. It could offer some facilities like setting the window's icon that GLUTs don't really.

By being a complete replacement for GLUT it would be easier to maintain GLUI since it wouldn't have to assume that the state of GLUT is unknown at all times.

I've not shared this feeling. But I felt like doing so here. Because I'm wondering with your experience with Travis and if things get anymore complicated, if instead GLUI could switch to a system where it provides many binaries (via an auto-built environment) so that users don't have to take on the burden of its dependencies (which might rapidly change) and so the scope of the GLUI project could be more of an effort to prepackage binaries so GLUI can be a full headers+binaries SDK.

In that case, how the fonts come about is not a problem for the users. And we would just have to manage a single build environment. I think figuring out this kind of thing could be important to forming a more organizational like effort. Eventually the kind of project's I'm interested in always come face-to-face with problems of scale. I think it would be interesting to try to think in these terms at this stage.

Ensuring you have working packages on every flavor of everything (which largely excludes Windows because it doesn't have a package framework) and those systems have all the dependencies covered is not the same as knowing you have working and complete binaries and the same for dependencies for developers to build against. (The Blender Foundation keeps something like this because building all of the dependencies is too error prone and labor intensive.)

**Comment by nigels-com** [comment]
libdrawtest is a small C library amounting to a handful of source files that can be copied into the GLUI repo.  It is not something complex and build-system intensive such as boost or Qt.  The intention is to bake font textures, rather than depend on freetype at runtime.  Here is a sample of a [Linux Libertine](http://www.linuxlibertine.org/) font texture for the ASCII range.  As a PNG around 50KiB, probably a similar footprint as gzipped PGM.

I don't regard this option as significant complication, from a build perspective.

linux-biolinum_s96_r0020-007f

**Comment by nigels-com** [comment]
On the theme of cross-platform build dependencies.  There is a [PR](https://github.com/nigels-com/glew/pull/151) over at GLEW to support the [Conan](https://conan.io/) infrastructure, seems like something similar to brew for Mac or apt-get for Ubuntu.

Completely decoupling GLUI from GLUT with alternative back-ends is a possibility.  If Conan is an enabler for that sort of scenario - GLUI on Qt, or GLUI on wxWidgets, perhaps so...

**Comment by nigels-com** [comment]
I think not.  I want the same pixels on the screen, regardless of the platform.  I don't want to be forever chasing glyphs that happen to be missing on this platform or the other, or only sorta-kinda match some other font.

**Comment by nigels-com** [comment]
I think libdrawtext is providing a texture-font alternative to GLUT bitmap fonts.  We could contribute something similar as a FreeGLUT extension, but it's not clear if FreeGLUT wants to embrace UTF-8.

**Pull request merged**
